/********************************************************************************
** Form generated from reading UI file 'quadcopter_mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_QUADCOPTER_MAINWINDOW_H
#define UI_QUADCOPTER_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDial>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Quadcopter_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *pushButton_DroneSelectPrevious;
    QPushButton *pushButton_DroneSelectNext;
    QGraphicsView *graphicsView_DroneCameraView;
    QLabel *label_Time;
    QPushButton *pushButton_DroneCameraSnapshot;
    QSlider *verticalSlider_Throttle;
    QPushButton *pushButton_MoveForward;
    QPushButton *pushButton_MoveLeft;
    QPushButton *pushButton_MoveReverse;
    QPushButton *pushButton_MoveRight;
    QDial *dial_AdjustDirection;
    QWidget *layoutWidget;
    QGridLayout *gridLayout_3;
    QGridLayout *gridLayout_2;
    QPushButton *pushButton_ConnectLoRaWAN;
    QLabel *label_MQTTStatus;
    QSpacerItem *verticalSpacer_3;
    QPushButton *pushButton_ConnectServer;
    QLabel *label_MQTTTopic;
    QLabel *label_MQTTQoS;
    QSpacerItem *verticalSpacer;
    QPlainTextEdit *plainTextEdit_LogPanel;
    QPushButton *pushButton_SaveLogFile;
    QGraphicsView *graphicsView_Camera3;
    QGraphicsView *graphicsView_Camera4;
    QGraphicsView *graphicsView_Camera2;
    QGraphicsView *graphicsView_Camera1;
    QGraphicsView *graphicsView_Camera0;
    QLabel *label_Logo;
    QLabel *label_Camera1;
    QLabel *label_Camera2;
    QLabel *label_Camera3;
    QLabel *label_Camera4;
    QLabel *label_Camera5;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_36;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_83;
    QLabel *label_85;
    QLabel *label_86;
    QLabel *label_88;
    QLabel *label_95;
    QLabel *label_97;
    QLabel *label_98;
    QLabel *label_99;
    QLabel *label_100;
    QLabel *label_82;
    QLabel *label_84;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_96;
    QLabel *label_QuadcopterConsole;
    QLabel *label_Compass;
    QLabel *label_DroneCameraView;
    QLabel *label_Camera1_2;
    QLabel *label_Camera2_2;
    QLabel *label_Camera3_2;
    QLabel *label_Camera5_2;
    QLabel *label_Camera4_2;

    void setupUi(QMainWindow *Quadcopter_MainWindow)
    {
        if (Quadcopter_MainWindow->objectName().isEmpty())
            Quadcopter_MainWindow->setObjectName("Quadcopter_MainWindow");
        Quadcopter_MainWindow->setEnabled(true);
        Quadcopter_MainWindow->resize(1280, 640);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Quadcopter_MainWindow->sizePolicy().hasHeightForWidth());
        Quadcopter_MainWindow->setSizePolicy(sizePolicy);
        QPalette palette;
        QBrush brush(QColor(248, 248, 248, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        Quadcopter_MainWindow->setPalette(palette);
        Quadcopter_MainWindow->setStyleSheet(QString::fromUtf8(""));
        centralwidget = new QWidget(Quadcopter_MainWindow);
        centralwidget->setObjectName("centralwidget");
        pushButton_DroneSelectPrevious = new QPushButton(centralwidget);
        pushButton_DroneSelectPrevious->setObjectName("pushButton_DroneSelectPrevious");
        pushButton_DroneSelectPrevious->setGeometry(QRect(498, 423, 50, 50));
        pushButton_DroneSelectPrevious->setStyleSheet(QString::fromUtf8("image: url(:/Resources/Icons/CameraPrevious.png);"));
        pushButton_DroneSelectPrevious->setAutoDefault(false);
        pushButton_DroneSelectNext = new QPushButton(centralwidget);
        pushButton_DroneSelectNext->setObjectName("pushButton_DroneSelectNext");
        pushButton_DroneSelectNext->setGeometry(QRect(758, 423, 50, 50));
        pushButton_DroneSelectNext->setBaseSize(QSize(50, 50));
        pushButton_DroneSelectNext->setStyleSheet(QString::fromUtf8("image: url(:/Resources/Icons/CameraNext.png);"));
        graphicsView_DroneCameraView = new QGraphicsView(centralwidget);
        graphicsView_DroneCameraView->setObjectName("graphicsView_DroneCameraView");
        graphicsView_DroneCameraView->setGeometry(QRect(330, 10, 651, 480));
        graphicsView_DroneCameraView->setStyleSheet(QString::fromUtf8(""));
        graphicsView_DroneCameraView->setFrameShape(QFrame::VLine);
        graphicsView_DroneCameraView->setFrameShadow(QFrame::Raised);
        label_Time = new QLabel(centralwidget);
        label_Time->setObjectName("label_Time");
        label_Time->setGeometry(QRect(860, 20, 111, 41));
        QFont font;
        font.setFamilies({QString::fromUtf8("Calibri")});
        label_Time->setFont(font);
        label_Time->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        label_Time->setScaledContents(false);
        pushButton_DroneCameraSnapshot = new QPushButton(centralwidget);
        pushButton_DroneCameraSnapshot->setObjectName("pushButton_DroneCameraSnapshot");
        pushButton_DroneCameraSnapshot->setGeometry(QRect(628, 423, 50, 50));
        pushButton_DroneCameraSnapshot->setStyleSheet(QString::fromUtf8("image: url(:/Resources/Icons/CameraShutter.png);"));
        verticalSlider_Throttle = new QSlider(centralwidget);
        verticalSlider_Throttle->setObjectName("verticalSlider_Throttle");
        verticalSlider_Throttle->setEnabled(true);
        verticalSlider_Throttle->setGeometry(QRect(350, 30, 41, 451));
        verticalSlider_Throttle->setStyleSheet(QString::fromUtf8("background-color: rgb(6, 15, 186);"));
        verticalSlider_Throttle->setMaximum(300);
        verticalSlider_Throttle->setOrientation(Qt::Vertical);
        verticalSlider_Throttle->setInvertedAppearance(false);
        verticalSlider_Throttle->setInvertedControls(false);
        verticalSlider_Throttle->setTickPosition(QSlider::TicksBothSides);
        verticalSlider_Throttle->setTickInterval(10);
        pushButton_MoveForward = new QPushButton(centralwidget);
        pushButton_MoveForward->setObjectName("pushButton_MoveForward");
        pushButton_MoveForward->setGeometry(QRect(110, 110, 110, 100));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Calibri")});
        font1.setPointSize(14);
        pushButton_MoveForward->setFont(font1);
        pushButton_MoveForward->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_MoveForward->setStyleSheet(QString::fromUtf8("background-image: url(:/Resources/Textures/steel texture_2.jpg);"));
        pushButton_MoveLeft = new QPushButton(centralwidget);
        pushButton_MoveLeft->setObjectName("pushButton_MoveLeft");
        pushButton_MoveLeft->setGeometry(QRect(10, 210, 100, 110));
        pushButton_MoveLeft->setFont(font1);
        pushButton_MoveLeft->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_MoveLeft->setStyleSheet(QString::fromUtf8("background-image: url(:/Resources/Textures/steel texture_2.jpg);"));
        pushButton_MoveReverse = new QPushButton(centralwidget);
        pushButton_MoveReverse->setObjectName("pushButton_MoveReverse");
        pushButton_MoveReverse->setGeometry(QRect(110, 320, 110, 100));
        pushButton_MoveReverse->setFont(font1);
        pushButton_MoveReverse->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_MoveReverse->setStyleSheet(QString::fromUtf8("background-image: url(:/Resources/Textures/steel texture_2.jpg);"));
        pushButton_MoveRight = new QPushButton(centralwidget);
        pushButton_MoveRight->setObjectName("pushButton_MoveRight");
        pushButton_MoveRight->setGeometry(QRect(220, 210, 100, 110));
        pushButton_MoveRight->setFont(font1);
        pushButton_MoveRight->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_MoveRight->setStyleSheet(QString::fromUtf8("background-image: url(:/Resources/Textures/steel texture_2.jpg);"));
        dial_AdjustDirection = new QDial(centralwidget);
        dial_AdjustDirection->setObjectName("dial_AdjustDirection");
        dial_AdjustDirection->setGeometry(QRect(132, 232, 65, 65));
        dial_AdjustDirection->setCursor(QCursor(Qt::CrossCursor));
        dial_AdjustDirection->setStyleSheet(QString::fromUtf8(""));
        dial_AdjustDirection->setMaximum(360);
        dial_AdjustDirection->setSingleStep(10);
        dial_AdjustDirection->setValue(180);
        dial_AdjustDirection->setTracking(true);
        dial_AdjustDirection->setWrapping(true);
        dial_AdjustDirection->setNotchesVisible(false);
        layoutWidget = new QWidget(centralwidget);
        layoutWidget->setObjectName("layoutWidget");
        layoutWidget->setGeometry(QRect(990, 10, 285, 611));
        gridLayout_3 = new QGridLayout(layoutWidget);
        gridLayout_3->setObjectName("gridLayout_3");
        gridLayout_3->setContentsMargins(0, 0, 0, 0);
        gridLayout_2 = new QGridLayout();
        gridLayout_2->setObjectName("gridLayout_2");
        pushButton_ConnectLoRaWAN = new QPushButton(layoutWidget);
        pushButton_ConnectLoRaWAN->setObjectName("pushButton_ConnectLoRaWAN");
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Calibri Light")});
        font2.setPointSize(12);
        pushButton_ConnectLoRaWAN->setFont(font2);
        pushButton_ConnectLoRaWAN->setStyleSheet(QString::fromUtf8(""));

        gridLayout_2->addWidget(pushButton_ConnectLoRaWAN, 1, 1, 1, 1);

        label_MQTTStatus = new QLabel(layoutWidget);
        label_MQTTStatus->setObjectName("label_MQTTStatus");
        QFont font3;
        font3.setFamilies({QString::fromUtf8("Calibri Light")});
        label_MQTTStatus->setFont(font3);

        gridLayout_2->addWidget(label_MQTTStatus, 8, 0, 1, 1);

        verticalSpacer_3 = new QSpacerItem(20, 10, QSizePolicy::Minimum, QSizePolicy::Fixed);

        gridLayout_2->addItem(verticalSpacer_3, 8, 1, 1, 1);

        pushButton_ConnectServer = new QPushButton(layoutWidget);
        pushButton_ConnectServer->setObjectName("pushButton_ConnectServer");
        pushButton_ConnectServer->setFont(font2);

        gridLayout_2->addWidget(pushButton_ConnectServer, 1, 0, 1, 1);

        label_MQTTTopic = new QLabel(layoutWidget);
        label_MQTTTopic->setObjectName("label_MQTTTopic");
        label_MQTTTopic->setFont(font3);

        gridLayout_2->addWidget(label_MQTTTopic, 6, 0, 1, 1);

        label_MQTTQoS = new QLabel(layoutWidget);
        label_MQTTQoS->setObjectName("label_MQTTQoS");
        label_MQTTQoS->setFont(font3);

        gridLayout_2->addWidget(label_MQTTQoS, 7, 0, 1, 1);


        gridLayout_3->addLayout(gridLayout_2, 1, 0, 1, 1);

        verticalSpacer = new QSpacerItem(20, 10, QSizePolicy::Minimum, QSizePolicy::Fixed);

        gridLayout_3->addItem(verticalSpacer, 0, 0, 1, 1);

        plainTextEdit_LogPanel = new QPlainTextEdit(layoutWidget);
        plainTextEdit_LogPanel->setObjectName("plainTextEdit_LogPanel");
        plainTextEdit_LogPanel->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 50, 50);\n"
"color: rgb(74, 148, 0);"));
        plainTextEdit_LogPanel->setFrameShape(QFrame::StyledPanel);
        plainTextEdit_LogPanel->setFrameShadow(QFrame::Plain);
        plainTextEdit_LogPanel->setTabChangesFocus(false);

        gridLayout_3->addWidget(plainTextEdit_LogPanel, 3, 0, 1, 1);

        pushButton_SaveLogFile = new QPushButton(layoutWidget);
        pushButton_SaveLogFile->setObjectName("pushButton_SaveLogFile");
        QFont font4;
        font4.setFamilies({QString::fromUtf8("Calibri Light")});
        font4.setPointSize(14);
        pushButton_SaveLogFile->setFont(font4);

        gridLayout_3->addWidget(pushButton_SaveLogFile, 4, 0, 1, 1);

        graphicsView_Camera3 = new QGraphicsView(centralwidget);
        graphicsView_Camera3->setObjectName("graphicsView_Camera3");
        graphicsView_Camera3->setGeometry(QRect(720, 520, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera3->sizePolicy().hasHeightForWidth());
        graphicsView_Camera3->setSizePolicy(sizePolicy);
        graphicsView_Camera3->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera3->setFrameShadow(QFrame::Plain);
        graphicsView_Camera4 = new QGraphicsView(centralwidget);
        graphicsView_Camera4->setObjectName("graphicsView_Camera4");
        graphicsView_Camera4->setGeometry(QRect(850, 520, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera4->sizePolicy().hasHeightForWidth());
        graphicsView_Camera4->setSizePolicy(sizePolicy);
        graphicsView_Camera4->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera4->setFrameShadow(QFrame::Plain);
        graphicsView_Camera2 = new QGraphicsView(centralwidget);
        graphicsView_Camera2->setObjectName("graphicsView_Camera2");
        graphicsView_Camera2->setGeometry(QRect(590, 520, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera2->sizePolicy().hasHeightForWidth());
        graphicsView_Camera2->setSizePolicy(sizePolicy);
        graphicsView_Camera2->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera2->setFrameShadow(QFrame::Plain);
        graphicsView_Camera1 = new QGraphicsView(centralwidget);
        graphicsView_Camera1->setObjectName("graphicsView_Camera1");
        graphicsView_Camera1->setEnabled(true);
        graphicsView_Camera1->setGeometry(QRect(460, 520, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera1->sizePolicy().hasHeightForWidth());
        graphicsView_Camera1->setSizePolicy(sizePolicy);
        graphicsView_Camera1->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera1->setFrameShadow(QFrame::Plain);
        graphicsView_Camera0 = new QGraphicsView(centralwidget);
        graphicsView_Camera0->setObjectName("graphicsView_Camera0");
        graphicsView_Camera0->setGeometry(QRect(330, 520, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera0->sizePolicy().hasHeightForWidth());
        graphicsView_Camera0->setSizePolicy(sizePolicy);
        graphicsView_Camera0->setStyleSheet(QString::fromUtf8(""));
        graphicsView_Camera0->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera0->setFrameShadow(QFrame::Plain);
        label_Logo = new QLabel(centralwidget);
        label_Logo->setObjectName("label_Logo");
        label_Logo->setGeometry(QRect(100, 510, 131, 91));
        label_Logo->setStyleSheet(QString::fromUtf8(""));
        label_Logo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Logo/MEND0Z0 LOGO_simple.png")));
        label_Logo->setScaledContents(true);
        label_Camera1 = new QLabel(centralwidget);
        label_Camera1->setObjectName("label_Camera1");
        label_Camera1->setGeometry(QRect(330, 500, 128, 121));
        label_Camera1->setStyleSheet(QString::fromUtf8(""));
        label_Camera1->setFrameShape(QFrame::Panel);
        label_Camera2 = new QLabel(centralwidget);
        label_Camera2->setObjectName("label_Camera2");
        label_Camera2->setGeometry(QRect(460, 500, 128, 121));
        label_Camera2->setFrameShape(QFrame::Panel);
        label_Camera3 = new QLabel(centralwidget);
        label_Camera3->setObjectName("label_Camera3");
        label_Camera3->setGeometry(QRect(590, 500, 128, 121));
        label_Camera3->setFrameShape(QFrame::Panel);
        label_Camera4 = new QLabel(centralwidget);
        label_Camera4->setObjectName("label_Camera4");
        label_Camera4->setGeometry(QRect(720, 500, 128, 121));
        label_Camera4->setFrameShape(QFrame::Panel);
        label_Camera5 = new QLabel(centralwidget);
        label_Camera5->setObjectName("label_Camera5");
        label_Camera5->setGeometry(QRect(850, 500, 128, 121));
        label_Camera5->setFrameShape(QFrame::Panel);
        label = new QLabel(centralwidget);
        label->setObjectName("label");
        label->setGeometry(QRect(120, 160, 10, 10));
        label->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label->setScaledContents(true);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(140, 165, 10, 10));
        label_2->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_2->setScaledContents(true);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(180, 165, 10, 10));
        label_4->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_4->setScaledContents(true);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(200, 160, 10, 10));
        label_5->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_5->setScaledContents(true);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(130, 150, 10, 10));
        label_6->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_6->setScaledContents(true);
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(150, 150, 10, 10));
        label_7->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_7->setScaledContents(true);
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(170, 150, 10, 10));
        label_8->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_8->setScaledContents(true);
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(190, 150, 10, 10));
        label_9->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_9->setScaledContents(true);
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(140, 140, 10, 10));
        label_10->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_10->setScaledContents(true);
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(160, 140, 10, 10));
        label_11->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_11->setScaledContents(true);
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(180, 140, 10, 10));
        label_12->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_12->setScaledContents(true);
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(150, 130, 10, 10));
        label_13->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_13->setScaledContents(true);
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(170, 130, 10, 10));
        label_14->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_14->setScaledContents(true);
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(160, 120, 10, 10));
        label_15->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_15->setScaledContents(true);
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(120, 175, 10, 10));
        label_16->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_16->setScaledContents(true);
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(200, 175, 10, 10));
        label_17->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_17->setScaledContents(true);
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(160, 160, 10, 10));
        label_18->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_18->setScaledContents(true);
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(160, 400, 10, 10));
        label_21->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_21->setScaledContents(true);
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(120, 345, 10, 10));
        label_22->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_22->setScaledContents(true);
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(180, 355, 10, 10));
        label_23->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_23->setScaledContents(true);
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(130, 370, 10, 10));
        label_24->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_24->setScaledContents(true);
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(140, 380, 10, 10));
        label_25->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_25->setScaledContents(true);
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(190, 370, 10, 10));
        label_26->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_26->setScaledContents(true);
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(200, 345, 10, 10));
        label_27->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_27->setScaledContents(true);
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(200, 360, 10, 10));
        label_28->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_28->setScaledContents(true);
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(180, 380, 10, 10));
        label_29->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_29->setScaledContents(true);
        label_30 = new QLabel(centralwidget);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(150, 390, 10, 10));
        label_30->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_30->setScaledContents(true);
        label_31 = new QLabel(centralwidget);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(170, 390, 10, 10));
        label_31->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_31->setScaledContents(true);
        label_32 = new QLabel(centralwidget);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(160, 345, 10, 10));
        label_32->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_32->setScaledContents(true);
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(160, 380, 10, 10));
        label_33->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_33->setScaledContents(true);
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(170, 370, 10, 10));
        label_34->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_34->setScaledContents(true);
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(160, 360, 10, 10));
        label_36->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_36->setScaledContents(true);
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(150, 370, 10, 10));
        label_38->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_38->setScaledContents(true);
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(120, 360, 10, 10));
        label_39->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_39->setScaledContents(true);
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(140, 355, 10, 10));
        label_40->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_40->setScaledContents(true);
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(290, 250, 10, 10));
        label_41->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_41->setScaledContents(true);
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(245, 220, 10, 10));
        label_43->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_43->setScaledContents(true);
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(245, 260, 10, 10));
        label_44->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_44->setScaledContents(true);
        label_45 = new QLabel(centralwidget);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(255, 240, 10, 10));
        label_45->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_45->setScaledContents(true);
        label_46 = new QLabel(centralwidget);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(280, 260, 10, 10));
        label_46->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_46->setScaledContents(true);
        label_47 = new QLabel(centralwidget);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(290, 270, 10, 10));
        label_47->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_47->setScaledContents(true);
        label_48 = new QLabel(centralwidget);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(300, 260, 10, 10));
        label_48->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_48->setScaledContents(true);
        label_49 = new QLabel(centralwidget);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(280, 240, 10, 10));
        label_49->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_49->setScaledContents(true);
        label_50 = new QLabel(centralwidget);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(260, 220, 10, 10));
        label_50->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_50->setScaledContents(true);
        label_51 = new QLabel(centralwidget);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(270, 290, 10, 10));
        label_51->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_51->setScaledContents(true);
        label_52 = new QLabel(centralwidget);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(270, 270, 10, 10));
        label_52->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_52->setScaledContents(true);
        label_53 = new QLabel(centralwidget);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(270, 230, 10, 10));
        label_53->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_53->setScaledContents(true);
        label_54 = new QLabel(centralwidget);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(270, 250, 10, 10));
        label_54->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_54->setScaledContents(true);
        label_55 = new QLabel(centralwidget);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(255, 280, 10, 10));
        label_55->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_55->setScaledContents(true);
        label_57 = new QLabel(centralwidget);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(280, 280, 10, 10));
        label_57->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_57->setScaledContents(true);
        label_58 = new QLabel(centralwidget);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(260, 260, 10, 10));
        label_58->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_58->setScaledContents(true);
        label_59 = new QLabel(centralwidget);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(245, 300, 10, 10));
        label_59->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_59->setScaledContents(true);
        label_60 = new QLabel(centralwidget);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(260, 300, 10, 10));
        label_60->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_60->setScaledContents(true);
        label_62 = new QLabel(centralwidget);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(75, 300, 10, 10));
        label_62->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_62->setScaledContents(true);
        label_63 = new QLabel(centralwidget);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(65, 280, 10, 10));
        label_63->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_63->setScaledContents(true);
        label_64 = new QLabel(centralwidget);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(75, 220, 10, 10));
        label_64->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_64->setScaledContents(true);
        label_65 = new QLabel(centralwidget);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(50, 250, 10, 10));
        label_65->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_65->setScaledContents(true);
        label_67 = new QLabel(centralwidget);
        label_67->setObjectName("label_67");
        label_67->setGeometry(QRect(60, 300, 10, 10));
        label_67->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_67->setScaledContents(true);
        label_68 = new QLabel(centralwidget);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(40, 240, 10, 10));
        label_68->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_68->setScaledContents(true);
        label_69 = new QLabel(centralwidget);
        label_69->setObjectName("label_69");
        label_69->setGeometry(QRect(20, 260, 10, 10));
        label_69->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_69->setScaledContents(true);
        label_70 = new QLabel(centralwidget);
        label_70->setObjectName("label_70");
        label_70->setGeometry(QRect(50, 230, 10, 10));
        label_70->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_70->setScaledContents(true);
        label_71 = new QLabel(centralwidget);
        label_71->setObjectName("label_71");
        label_71->setGeometry(QRect(30, 270, 10, 10));
        label_71->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_71->setScaledContents(true);
        label_72 = new QLabel(centralwidget);
        label_72->setObjectName("label_72");
        label_72->setGeometry(QRect(50, 290, 10, 10));
        label_72->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_72->setScaledContents(true);
        label_73 = new QLabel(centralwidget);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(30, 250, 10, 10));
        label_73->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_73->setScaledContents(true);
        label_74 = new QLabel(centralwidget);
        label_74->setObjectName("label_74");
        label_74->setGeometry(QRect(50, 270, 10, 10));
        label_74->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_74->setScaledContents(true);
        label_75 = new QLabel(centralwidget);
        label_75->setObjectName("label_75");
        label_75->setGeometry(QRect(40, 280, 10, 10));
        label_75->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_75->setScaledContents(true);
        label_76 = new QLabel(centralwidget);
        label_76->setObjectName("label_76");
        label_76->setGeometry(QRect(40, 260, 10, 10));
        label_76->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_76->setScaledContents(true);
        label_78 = new QLabel(centralwidget);
        label_78->setObjectName("label_78");
        label_78->setGeometry(QRect(60, 260, 10, 10));
        label_78->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_78->setScaledContents(true);
        label_79 = new QLabel(centralwidget);
        label_79->setObjectName("label_79");
        label_79->setGeometry(QRect(65, 240, 10, 10));
        label_79->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_79->setScaledContents(true);
        label_80 = new QLabel(centralwidget);
        label_80->setObjectName("label_80");
        label_80->setGeometry(QRect(60, 220, 10, 10));
        label_80->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_80->setScaledContents(true);
        label_81 = new QLabel(centralwidget);
        label_81->setObjectName("label_81");
        label_81->setGeometry(QRect(120, 190, 10, 10));
        label_81->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_81->setScaledContents(true);
        label_83 = new QLabel(centralwidget);
        label_83->setObjectName("label_83");
        label_83->setGeometry(QRect(200, 190, 10, 10));
        label_83->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_83->setScaledContents(true);
        label_85 = new QLabel(centralwidget);
        label_85->setObjectName("label_85");
        label_85->setGeometry(QRect(160, 175, 10, 10));
        label_85->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_85->setScaledContents(true);
        label_86 = new QLabel(centralwidget);
        label_86->setObjectName("label_86");
        label_86->setGeometry(QRect(140, 180, 10, 10));
        label_86->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_86->setScaledContents(true);
        label_88 = new QLabel(centralwidget);
        label_88->setObjectName("label_88");
        label_88->setGeometry(QRect(180, 180, 10, 10));
        label_88->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_88->setScaledContents(true);
        label_95 = new QLabel(centralwidget);
        label_95->setObjectName("label_95");
        label_95->setGeometry(QRect(80, 240, 10, 10));
        label_95->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_95->setScaledContents(true);
        label_97 = new QLabel(centralwidget);
        label_97->setObjectName("label_97");
        label_97->setGeometry(QRect(80, 280, 10, 10));
        label_97->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_97->setScaledContents(true);
        label_98 = new QLabel(centralwidget);
        label_98->setObjectName("label_98");
        label_98->setGeometry(QRect(90, 220, 10, 10));
        label_98->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_98->setScaledContents(true);
        label_99 = new QLabel(centralwidget);
        label_99->setObjectName("label_99");
        label_99->setGeometry(QRect(90, 300, 10, 10));
        label_99->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_99->setScaledContents(true);
        label_100 = new QLabel(centralwidget);
        label_100->setObjectName("label_100");
        label_100->setGeometry(QRect(75, 260, 10, 10));
        label_100->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_100->setScaledContents(true);
        label_82 = new QLabel(centralwidget);
        label_82->setObjectName("label_82");
        label_82->setGeometry(QRect(240, 280, 10, 10));
        label_82->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_82->setScaledContents(true);
        label_84 = new QLabel(centralwidget);
        label_84->setObjectName("label_84");
        label_84->setGeometry(QRect(230, 300, 10, 10));
        label_84->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_84->setScaledContents(true);
        label_89 = new QLabel(centralwidget);
        label_89->setObjectName("label_89");
        label_89->setGeometry(QRect(240, 240, 10, 10));
        label_89->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_89->setScaledContents(true);
        label_90 = new QLabel(centralwidget);
        label_90->setObjectName("label_90");
        label_90->setGeometry(QRect(230, 220, 10, 10));
        label_90->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_90->setScaledContents(true);
        label_91 = new QLabel(centralwidget);
        label_91->setObjectName("label_91");
        label_91->setGeometry(QRect(120, 330, 10, 10));
        label_91->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_91->setScaledContents(true);
        label_92 = new QLabel(centralwidget);
        label_92->setObjectName("label_92");
        label_92->setGeometry(QRect(200, 330, 10, 10));
        label_92->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_92->setScaledContents(true);
        label_93 = new QLabel(centralwidget);
        label_93->setObjectName("label_93");
        label_93->setGeometry(QRect(180, 340, 10, 10));
        label_93->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_93->setScaledContents(true);
        label_96 = new QLabel(centralwidget);
        label_96->setObjectName("label_96");
        label_96->setGeometry(QRect(140, 340, 10, 10));
        label_96->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_96->setScaledContents(true);
        label_QuadcopterConsole = new QLabel(centralwidget);
        label_QuadcopterConsole->setObjectName("label_QuadcopterConsole");
        label_QuadcopterConsole->setGeometry(QRect(50, 30, 241, 41));
        label_QuadcopterConsole->setFrameShape(QFrame::Box);
        label_Compass = new QLabel(centralwidget);
        label_Compass->setObjectName("label_Compass");
        label_Compass->setGeometry(QRect(112, 215, 102, 102));
        label_Compass->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Icons/Compass.png")));
        label_Compass->setScaledContents(true);
        label_DroneCameraView = new QLabel(centralwidget);
        label_DroneCameraView->setObjectName("label_DroneCameraView");
        label_DroneCameraView->setGeometry(QRect(330, 10, 651, 481));
        label_DroneCameraView->setScaledContents(true);
        label_Camera1_2 = new QLabel(centralwidget);
        label_Camera1_2->setObjectName("label_Camera1_2");
        label_Camera1_2->setGeometry(QRect(330, 520, 124, 90));
        label_Camera1_2->setScaledContents(true);
        label_Camera2_2 = new QLabel(centralwidget);
        label_Camera2_2->setObjectName("label_Camera2_2");
        label_Camera2_2->setGeometry(QRect(460, 520, 124, 90));
        label_Camera2_2->setScaledContents(true);
        label_Camera3_2 = new QLabel(centralwidget);
        label_Camera3_2->setObjectName("label_Camera3_2");
        label_Camera3_2->setGeometry(QRect(590, 520, 124, 90));
        label_Camera3_2->setScaledContents(true);
        label_Camera5_2 = new QLabel(centralwidget);
        label_Camera5_2->setObjectName("label_Camera5_2");
        label_Camera5_2->setGeometry(QRect(850, 520, 124, 90));
        label_Camera5_2->setScaledContents(true);
        label_Camera4_2 = new QLabel(centralwidget);
        label_Camera4_2->setObjectName("label_Camera4_2");
        label_Camera4_2->setGeometry(QRect(720, 520, 124, 90));
        label_Camera4_2->setScaledContents(true);
        Quadcopter_MainWindow->setCentralWidget(centralwidget);
        label_Camera5_2->raise();
        label_Camera4_2->raise();
        label_Camera3_2->raise();
        label_Camera2_2->raise();
        label_Camera1_2->raise();
        label_DroneCameraView->raise();
        pushButton_MoveLeft->raise();
        label_Compass->raise();
        pushButton_MoveForward->raise();
        label_Camera5->raise();
        label_Camera4->raise();
        label_Camera3->raise();
        label_Camera2->raise();
        label_Camera1->raise();
        graphicsView_DroneCameraView->raise();
        graphicsView_Camera3->raise();
        graphicsView_Camera4->raise();
        graphicsView_Camera2->raise();
        graphicsView_Camera1->raise();
        graphicsView_Camera0->raise();
        pushButton_MoveReverse->raise();
        pushButton_MoveRight->raise();
        dial_AdjustDirection->raise();
        layoutWidget->raise();
        pushButton_DroneSelectPrevious->raise();
        pushButton_DroneSelectNext->raise();
        label_Time->raise();
        pushButton_DroneCameraSnapshot->raise();
        verticalSlider_Throttle->raise();
        label_Logo->raise();
        label->raise();
        label_2->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        label_13->raise();
        label_14->raise();
        label_15->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        label_21->raise();
        label_22->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        label_28->raise();
        label_29->raise();
        label_30->raise();
        label_31->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_36->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_43->raise();
        label_44->raise();
        label_45->raise();
        label_46->raise();
        label_47->raise();
        label_48->raise();
        label_49->raise();
        label_50->raise();
        label_51->raise();
        label_52->raise();
        label_53->raise();
        label_54->raise();
        label_55->raise();
        label_57->raise();
        label_58->raise();
        label_59->raise();
        label_60->raise();
        label_62->raise();
        label_63->raise();
        label_64->raise();
        label_65->raise();
        label_67->raise();
        label_68->raise();
        label_69->raise();
        label_70->raise();
        label_71->raise();
        label_72->raise();
        label_73->raise();
        label_74->raise();
        label_75->raise();
        label_76->raise();
        label_78->raise();
        label_79->raise();
        label_80->raise();
        label_81->raise();
        label_83->raise();
        label_85->raise();
        label_86->raise();
        label_88->raise();
        label_95->raise();
        label_97->raise();
        label_98->raise();
        label_99->raise();
        label_100->raise();
        label_82->raise();
        label_84->raise();
        label_89->raise();
        label_90->raise();
        label_91->raise();
        label_92->raise();
        label_93->raise();
        label_96->raise();
        label_QuadcopterConsole->raise();

        retranslateUi(Quadcopter_MainWindow);

        QMetaObject::connectSlotsByName(Quadcopter_MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *Quadcopter_MainWindow)
    {
        Quadcopter_MainWindow->setWindowTitle(QCoreApplication::translate("Quadcopter_MainWindow", "Quadcopter_MainWindow", nullptr));
        pushButton_DroneSelectPrevious->setText(QString());
        pushButton_DroneSelectNext->setText(QString());
        label_Time->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#ffffff;\">00:00:00</span></p></body></html>", nullptr));
        pushButton_DroneCameraSnapshot->setText(QString());
        pushButton_MoveForward->setText(QString());
        pushButton_MoveLeft->setText(QString());
        pushButton_MoveReverse->setText(QString());
        pushButton_MoveRight->setText(QString());
        pushButton_ConnectLoRaWAN->setText(QCoreApplication::translate("Quadcopter_MainWindow", "Search Drones", nullptr));
        label_MQTTStatus->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Status: N/A</span></p></body></html>", nullptr));
        pushButton_ConnectServer->setText(QCoreApplication::translate("Quadcopter_MainWindow", "Connect Server", nullptr));
        label_MQTTTopic->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Topic: N/A</span></p></body></html>", nullptr));
        label_MQTTQoS->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">QoS: N/A</span></p></body></html>", nullptr));
        plainTextEdit_LogPanel->setPlainText(QString());
        pushButton_SaveLogFile->setText(QCoreApplication::translate("Quadcopter_MainWindow", "Save Log File", nullptr));
        label_Logo->setText(QString());
        label_Camera1->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 1</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_Camera2->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 2</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_Camera3->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 3</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_Camera4->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 4</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_Camera5->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 5</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label->setText(QString());
        label_2->setText(QString());
        label_4->setText(QString());
        label_5->setText(QString());
        label_6->setText(QString());
        label_7->setText(QString());
        label_8->setText(QString());
        label_9->setText(QString());
        label_10->setText(QString());
        label_11->setText(QString());
        label_12->setText(QString());
        label_13->setText(QString());
        label_14->setText(QString());
        label_15->setText(QString());
        label_16->setText(QString());
        label_17->setText(QString());
        label_18->setText(QString());
        label_21->setText(QString());
        label_22->setText(QString());
        label_23->setText(QString());
        label_24->setText(QString());
        label_25->setText(QString());
        label_26->setText(QString());
        label_27->setText(QString());
        label_28->setText(QString());
        label_29->setText(QString());
        label_30->setText(QString());
        label_31->setText(QString());
        label_32->setText(QString());
        label_33->setText(QString());
        label_34->setText(QString());
        label_36->setText(QString());
        label_38->setText(QString());
        label_39->setText(QString());
        label_40->setText(QString());
        label_41->setText(QString());
        label_43->setText(QString());
        label_44->setText(QString());
        label_45->setText(QString());
        label_46->setText(QString());
        label_47->setText(QString());
        label_48->setText(QString());
        label_49->setText(QString());
        label_50->setText(QString());
        label_51->setText(QString());
        label_52->setText(QString());
        label_53->setText(QString());
        label_54->setText(QString());
        label_55->setText(QString());
        label_57->setText(QString());
        label_58->setText(QString());
        label_59->setText(QString());
        label_60->setText(QString());
        label_62->setText(QString());
        label_63->setText(QString());
        label_64->setText(QString());
        label_65->setText(QString());
        label_67->setText(QString());
        label_68->setText(QString());
        label_69->setText(QString());
        label_70->setText(QString());
        label_71->setText(QString());
        label_72->setText(QString());
        label_73->setText(QString());
        label_74->setText(QString());
        label_75->setText(QString());
        label_76->setText(QString());
        label_78->setText(QString());
        label_79->setText(QString());
        label_80->setText(QString());
        label_81->setText(QString());
        label_83->setText(QString());
        label_85->setText(QString());
        label_86->setText(QString());
        label_88->setText(QString());
        label_95->setText(QString());
        label_97->setText(QString());
        label_98->setText(QString());
        label_99->setText(QString());
        label_100->setText(QString());
        label_82->setText(QString());
        label_84->setText(QString());
        label_89->setText(QString());
        label_90->setText(QString());
        label_91->setText(QString());
        label_92->setText(QString());
        label_93->setText(QString());
        label_96->setText(QString());
        label_QuadcopterConsole->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Quadcopter - Console</span></p></body></html>", nullptr));
        label_Compass->setText(QString());
        label_DroneCameraView->setText(QString());
        label_Camera1_2->setText(QString());
        label_Camera2_2->setText(QString());
        label_Camera3_2->setText(QString());
        label_Camera5_2->setText(QString());
        label_Camera4_2->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Quadcopter_MainWindow: public Ui_Quadcopter_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_QUADCOPTER_MAINWINDOW_H
