/********************************************************************************
** Form generated from reading UI file 'quadcopter_mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_QUADCOPTER_MAINWINDOW_H
#define UI_QUADCOPTER_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDial>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Quadcopter_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *pushButton_DroneSelectPrevious;
    QPushButton *pushButton_DroneSelectNext;
    QGraphicsView *graphicsView_DroneCameraView;
    QLabel *label_Time;
    QPushButton *pushButton_DroneCameraSnapshot;
    QSlider *verticalSlider_Throttle;
    QPushButton *pushButton_MoveForward;
    QPushButton *pushButton_MoveLeft;
    QPushButton *pushButton_MoveReverse;
    QPushButton *pushButton_MoveRight;
    QDial *dial_GeologicalPosition;
    QWidget *layoutWidget;
    QGridLayout *gridLayout_3;
    QGridLayout *gridLayout_2;
    QPushButton *pushButton_ConnectLoRaWAN;
    QLabel *label_Drones;
    QPushButton *pushButton_ServerSetting;
    QLabel *label_MQTTTopic;
    QLabel *label_MQTTQoS;
    QLabel *label_StatusMQTTServer;
    QLabel *label_StatusLoRaWANServer;
    QLabel *label_DronesNumber;
    QPushButton *pushButton_SaveLogFile;
    QPlainTextEdit *plainTextEdit_LogPanel;
    QLabel *label_QuadcopterConsole;
    QSpacerItem *verticalSpacer;
    QGraphicsView *graphicsView_Camera3;
    QGraphicsView *graphicsView_Camera4;
    QGraphicsView *graphicsView_Camera2;
    QGraphicsView *graphicsView_Camera1;
    QGraphicsView *graphicsView_Camera0;
    QLabel *label_Logo;
    QLabel *label_Camera1;
    QLabel *label_Camera2;
    QLabel *label_Camera3;
    QLabel *label_Camera4;
    QLabel *label_Camera5;
    QLabel *label_F31;
    QLabel *label_F22;
    QLabel *label_F24;
    QLabel *label_F34;
    QLabel *label_F41;
    QLabel *label_F32;
    QLabel *label_F33;
    QLabel *label_F43;
    QLabel *label_F51;
    QLabel *label_F42;
    QLabel *label_F52;
    QLabel *label_F61;
    QLabel *label_F62;
    QLabel *label_F71;
    QLabel *label_F21;
    QLabel *label_F25;
    QLabel *label_F23;
    QLabel *label_B71;
    QLabel *label_B25;
    QLabel *label_B22;
    QLabel *label_B43;
    QLabel *label_B52;
    QLabel *label_B41;
    QLabel *label_B21;
    QLabel *label_B31;
    QLabel *label_B51;
    QLabel *label_B62;
    QLabel *label_B61;
    QLabel *label_B13;
    QLabel *label_B42;
    QLabel *label_B32;
    QLabel *label_B23;
    QLabel *label_B33;
    QLabel *label_B34;
    QLabel *label_B24;
    QLabel *label_R61;
    QLabel *label_R21;
    QLabel *label_R13;
    QLabel *label_R22;
    QLabel *label_R42;
    QLabel *label_R62;
    QLabel *label_R71;
    QLabel *label_R51;
    QLabel *label_R31;
    QLabel *label_R43;
    QLabel *label_R33;
    QLabel *label_R41;
    QLabel *label_R32;
    QLabel *label_R24;
    QLabel *label_R52;
    QLabel *label_R23;
    QLabel *label_R25;
    QLabel *label_R34;
    QLabel *label_L21;
    QLabel *label_L22;
    QLabel *label_L25;
    QLabel *label_L33;
    QLabel *label_L31;
    QLabel *label_L52;
    QLabel *label_L71;
    QLabel *label_L43;
    QLabel *label_L61;
    QLabel *label_L41;
    QLabel *label_L62;
    QLabel *label_L32;
    QLabel *label_L51;
    QLabel *label_L42;
    QLabel *label_L23;
    QLabel *label_L24;
    QLabel *label_L34;
    QLabel *label_F11;
    QLabel *label_F15;
    QLabel *label_F13;
    QLabel *label_F12;
    QLabel *label_F14;
    QLabel *label_L14;
    QLabel *label_L12;
    QLabel *label_L15;
    QLabel *label_L11;
    QLabel *label_L13;
    QLabel *label_R14;
    QLabel *label_R15;
    QLabel *label_R12;
    QLabel *label_R11;
    QLabel *label_B15;
    QLabel *label_B11;
    QLabel *label_B12;
    QLabel *label_B14;
    QLabel *label_Compass;
    QLabel *label_DroneCameraView;
    QLabel *label_Camera1_2;
    QLabel *label_Camera2_2;
    QLabel *label_Camera3_2;
    QLabel *label_Camera5_2;
    QLabel *label_Camera4_2;
    QWidget *layoutWidget1;
    QGridLayout *gridLayout;
    QLCDNumber *lcdNumber_Height;
    QLCDNumber *lcdNumber_Speed;
    QLCDNumber *lcdNumber_Displacement;
    QLabel *label_Speed;
    QLabel *label_Displacement;
    QLabel *label_Height;
    QLabel *label_Pressure;
    QLCDNumber *lcdNumber_Pressure;
    QLabel *label_Humedity;
    QLCDNumber *lcdNumber_Humedity;
    QLCDNumber *lcdNumber_Temperature;
    QLabel *label_Temperature;
    QLCDNumber *lcdNumber_ThrottleValue;
    QProgressBar *progressBar_BatteryCharge;

    void setupUi(QMainWindow *Quadcopter_MainWindow)
    {
        if (Quadcopter_MainWindow->objectName().isEmpty())
            Quadcopter_MainWindow->setObjectName("Quadcopter_MainWindow");
        Quadcopter_MainWindow->setEnabled(true);
        Quadcopter_MainWindow->resize(1280, 720);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Quadcopter_MainWindow->sizePolicy().hasHeightForWidth());
        Quadcopter_MainWindow->setSizePolicy(sizePolicy);
        QPalette palette;
        QBrush brush(QColor(248, 248, 248, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        Quadcopter_MainWindow->setPalette(palette);
        Quadcopter_MainWindow->setStyleSheet(QString::fromUtf8(""));
        centralwidget = new QWidget(Quadcopter_MainWindow);
        centralwidget->setObjectName("centralwidget");
        pushButton_DroneSelectPrevious = new QPushButton(centralwidget);
        pushButton_DroneSelectPrevious->setObjectName("pushButton_DroneSelectPrevious");
        pushButton_DroneSelectPrevious->setGeometry(QRect(473, 463, 50, 50));
        pushButton_DroneSelectPrevious->setStyleSheet(QString::fromUtf8("image: url(:/Resources/Icons/CameraPrevious.png);"));
        pushButton_DroneSelectPrevious->setAutoDefault(false);
        pushButton_DroneSelectNext = new QPushButton(centralwidget);
        pushButton_DroneSelectNext->setObjectName("pushButton_DroneSelectNext");
        pushButton_DroneSelectNext->setGeometry(QRect(733, 463, 50, 50));
        pushButton_DroneSelectNext->setBaseSize(QSize(50, 50));
        pushButton_DroneSelectNext->setStyleSheet(QString::fromUtf8("image: url(:/Resources/Icons/CameraNext.png);"));
        graphicsView_DroneCameraView = new QGraphicsView(centralwidget);
        graphicsView_DroneCameraView->setObjectName("graphicsView_DroneCameraView");
        graphicsView_DroneCameraView->setGeometry(QRect(305, 50, 651, 480));
        graphicsView_DroneCameraView->setStyleSheet(QString::fromUtf8(""));
        graphicsView_DroneCameraView->setFrameShape(QFrame::VLine);
        graphicsView_DroneCameraView->setFrameShadow(QFrame::Raised);
        label_Time = new QLabel(centralwidget);
        label_Time->setObjectName("label_Time");
        label_Time->setGeometry(QRect(315, 60, 120, 40));
        QFont font;
        font.setFamilies({QString::fromUtf8("Calibri")});
        label_Time->setFont(font);
        label_Time->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        label_Time->setScaledContents(false);
        pushButton_DroneCameraSnapshot = new QPushButton(centralwidget);
        pushButton_DroneCameraSnapshot->setObjectName("pushButton_DroneCameraSnapshot");
        pushButton_DroneCameraSnapshot->setGeometry(QRect(603, 463, 50, 50));
        pushButton_DroneCameraSnapshot->setStyleSheet(QString::fromUtf8("image: url(:/Resources/Icons/CameraShutter.png);"));
        verticalSlider_Throttle = new QSlider(centralwidget);
        verticalSlider_Throttle->setObjectName("verticalSlider_Throttle");
        verticalSlider_Throttle->setEnabled(true);
        verticalSlider_Throttle->setGeometry(QRect(890, 60, 40, 420));
        verticalSlider_Throttle->setStyleSheet(QString::fromUtf8("background-color: rgb(6, 15, 186);"));
        verticalSlider_Throttle->setMaximum(300);
        verticalSlider_Throttle->setOrientation(Qt::Vertical);
        verticalSlider_Throttle->setInvertedAppearance(false);
        verticalSlider_Throttle->setInvertedControls(false);
        verticalSlider_Throttle->setTickPosition(QSlider::TicksBothSides);
        verticalSlider_Throttle->setTickInterval(10);
        pushButton_MoveForward = new QPushButton(centralwidget);
        pushButton_MoveForward->setObjectName("pushButton_MoveForward");
        pushButton_MoveForward->setGeometry(QRect(1060, 250, 110, 100));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Calibri")});
        font1.setPointSize(14);
        pushButton_MoveForward->setFont(font1);
        pushButton_MoveForward->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_MoveForward->setStyleSheet(QString::fromUtf8("background-image: url(:/Resources/Textures/steel texture_2.jpg);"));
        pushButton_MoveLeft = new QPushButton(centralwidget);
        pushButton_MoveLeft->setObjectName("pushButton_MoveLeft");
        pushButton_MoveLeft->setGeometry(QRect(960, 350, 100, 110));
        pushButton_MoveLeft->setFont(font1);
        pushButton_MoveLeft->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_MoveLeft->setStyleSheet(QString::fromUtf8("background-image: url(:/Resources/Textures/steel texture_2.jpg);"));
        pushButton_MoveReverse = new QPushButton(centralwidget);
        pushButton_MoveReverse->setObjectName("pushButton_MoveReverse");
        pushButton_MoveReverse->setGeometry(QRect(1060, 460, 110, 100));
        pushButton_MoveReverse->setFont(font1);
        pushButton_MoveReverse->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_MoveReverse->setStyleSheet(QString::fromUtf8("background-image: url(:/Resources/Textures/steel texture_2.jpg);"));
        pushButton_MoveRight = new QPushButton(centralwidget);
        pushButton_MoveRight->setObjectName("pushButton_MoveRight");
        pushButton_MoveRight->setGeometry(QRect(1170, 350, 100, 110));
        pushButton_MoveRight->setFont(font1);
        pushButton_MoveRight->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_MoveRight->setStyleSheet(QString::fromUtf8("background-image: url(:/Resources/Textures/steel texture_2.jpg);"));
        dial_GeologicalPosition = new QDial(centralwidget);
        dial_GeologicalPosition->setObjectName("dial_GeologicalPosition");
        dial_GeologicalPosition->setGeometry(QRect(1082, 372, 65, 65));
        dial_GeologicalPosition->setCursor(QCursor(Qt::CrossCursor));
        dial_GeologicalPosition->setStyleSheet(QString::fromUtf8(""));
        dial_GeologicalPosition->setMaximum(360);
        dial_GeologicalPosition->setSingleStep(10);
        dial_GeologicalPosition->setValue(180);
        dial_GeologicalPosition->setTracking(true);
        dial_GeologicalPosition->setWrapping(true);
        dial_GeologicalPosition->setNotchesVisible(false);
        layoutWidget = new QWidget(centralwidget);
        layoutWidget->setObjectName("layoutWidget");
        layoutWidget->setGeometry(QRect(10, 50, 285, 611));
        gridLayout_3 = new QGridLayout(layoutWidget);
        gridLayout_3->setObjectName("gridLayout_3");
        gridLayout_3->setContentsMargins(0, 0, 0, 0);
        gridLayout_2 = new QGridLayout();
        gridLayout_2->setObjectName("gridLayout_2");
        pushButton_ConnectLoRaWAN = new QPushButton(layoutWidget);
        pushButton_ConnectLoRaWAN->setObjectName("pushButton_ConnectLoRaWAN");
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Calibri Light")});
        font2.setPointSize(12);
        pushButton_ConnectLoRaWAN->setFont(font2);
        pushButton_ConnectLoRaWAN->setStyleSheet(QString::fromUtf8(""));

        gridLayout_2->addWidget(pushButton_ConnectLoRaWAN, 1, 1, 1, 1);

        label_Drones = new QLabel(layoutWidget);
        label_Drones->setObjectName("label_Drones");
        QFont font3;
        font3.setFamilies({QString::fromUtf8("Calibri Light")});
        label_Drones->setFont(font3);

        gridLayout_2->addWidget(label_Drones, 8, 0, 1, 1);

        pushButton_ServerSetting = new QPushButton(layoutWidget);
        pushButton_ServerSetting->setObjectName("pushButton_ServerSetting");
        pushButton_ServerSetting->setFont(font2);

        gridLayout_2->addWidget(pushButton_ServerSetting, 1, 0, 1, 1);

        label_MQTTTopic = new QLabel(layoutWidget);
        label_MQTTTopic->setObjectName("label_MQTTTopic");
        label_MQTTTopic->setFont(font3);

        gridLayout_2->addWidget(label_MQTTTopic, 6, 0, 1, 1);

        label_MQTTQoS = new QLabel(layoutWidget);
        label_MQTTQoS->setObjectName("label_MQTTQoS");
        label_MQTTQoS->setFont(font3);

        gridLayout_2->addWidget(label_MQTTQoS, 7, 0, 1, 1);

        label_StatusMQTTServer = new QLabel(layoutWidget);
        label_StatusMQTTServer->setObjectName("label_StatusMQTTServer");

        gridLayout_2->addWidget(label_StatusMQTTServer, 6, 1, 1, 1);

        label_StatusLoRaWANServer = new QLabel(layoutWidget);
        label_StatusLoRaWANServer->setObjectName("label_StatusLoRaWANServer");

        gridLayout_2->addWidget(label_StatusLoRaWANServer, 7, 1, 1, 1);

        label_DronesNumber = new QLabel(layoutWidget);
        label_DronesNumber->setObjectName("label_DronesNumber");

        gridLayout_2->addWidget(label_DronesNumber, 8, 1, 1, 1);


        gridLayout_3->addLayout(gridLayout_2, 3, 0, 1, 1);

        pushButton_SaveLogFile = new QPushButton(layoutWidget);
        pushButton_SaveLogFile->setObjectName("pushButton_SaveLogFile");
        QFont font4;
        font4.setFamilies({QString::fromUtf8("Calibri Light")});
        font4.setPointSize(14);
        pushButton_SaveLogFile->setFont(font4);

        gridLayout_3->addWidget(pushButton_SaveLogFile, 6, 0, 1, 1);

        plainTextEdit_LogPanel = new QPlainTextEdit(layoutWidget);
        plainTextEdit_LogPanel->setObjectName("plainTextEdit_LogPanel");
        plainTextEdit_LogPanel->setStyleSheet(QString::fromUtf8("background-color: rgb(50, 50, 50);"));
        plainTextEdit_LogPanel->setFrameShape(QFrame::StyledPanel);
        plainTextEdit_LogPanel->setFrameShadow(QFrame::Plain);
        plainTextEdit_LogPanel->setTabChangesFocus(false);

        gridLayout_3->addWidget(plainTextEdit_LogPanel, 5, 0, 1, 1);

        label_QuadcopterConsole = new QLabel(layoutWidget);
        label_QuadcopterConsole->setObjectName("label_QuadcopterConsole");
        label_QuadcopterConsole->setFrameShape(QFrame::Box);

        gridLayout_3->addWidget(label_QuadcopterConsole, 1, 0, 1, 1);

        verticalSpacer = new QSpacerItem(20, 10, QSizePolicy::Minimum, QSizePolicy::Fixed);

        gridLayout_3->addItem(verticalSpacer, 2, 0, 1, 1);

        graphicsView_Camera3 = new QGraphicsView(centralwidget);
        graphicsView_Camera3->setObjectName("graphicsView_Camera3");
        graphicsView_Camera3->setGeometry(QRect(695, 560, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera3->sizePolicy().hasHeightForWidth());
        graphicsView_Camera3->setSizePolicy(sizePolicy);
        graphicsView_Camera3->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera3->setFrameShadow(QFrame::Plain);
        graphicsView_Camera4 = new QGraphicsView(centralwidget);
        graphicsView_Camera4->setObjectName("graphicsView_Camera4");
        graphicsView_Camera4->setGeometry(QRect(825, 560, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera4->sizePolicy().hasHeightForWidth());
        graphicsView_Camera4->setSizePolicy(sizePolicy);
        graphicsView_Camera4->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera4->setFrameShadow(QFrame::Plain);
        graphicsView_Camera2 = new QGraphicsView(centralwidget);
        graphicsView_Camera2->setObjectName("graphicsView_Camera2");
        graphicsView_Camera2->setGeometry(QRect(565, 560, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera2->sizePolicy().hasHeightForWidth());
        graphicsView_Camera2->setSizePolicy(sizePolicy);
        graphicsView_Camera2->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera2->setFrameShadow(QFrame::Plain);
        graphicsView_Camera1 = new QGraphicsView(centralwidget);
        graphicsView_Camera1->setObjectName("graphicsView_Camera1");
        graphicsView_Camera1->setEnabled(true);
        graphicsView_Camera1->setGeometry(QRect(435, 560, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera1->sizePolicy().hasHeightForWidth());
        graphicsView_Camera1->setSizePolicy(sizePolicy);
        graphicsView_Camera1->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera1->setFrameShadow(QFrame::Plain);
        graphicsView_Camera0 = new QGraphicsView(centralwidget);
        graphicsView_Camera0->setObjectName("graphicsView_Camera0");
        graphicsView_Camera0->setGeometry(QRect(305, 560, 128, 96));
        sizePolicy.setHeightForWidth(graphicsView_Camera0->sizePolicy().hasHeightForWidth());
        graphicsView_Camera0->setSizePolicy(sizePolicy);
        graphicsView_Camera0->setStyleSheet(QString::fromUtf8(""));
        graphicsView_Camera0->setFrameShape(QFrame::StyledPanel);
        graphicsView_Camera0->setFrameShadow(QFrame::Plain);
        label_Logo = new QLabel(centralwidget);
        label_Logo->setObjectName("label_Logo");
        label_Logo->setGeometry(QRect(1050, 570, 131, 91));
        label_Logo->setStyleSheet(QString::fromUtf8(""));
        label_Logo->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Logo/MEND0Z0 LOGO_simple.png")));
        label_Logo->setScaledContents(true);
        label_Camera1 = new QLabel(centralwidget);
        label_Camera1->setObjectName("label_Camera1");
        label_Camera1->setGeometry(QRect(305, 540, 128, 121));
        label_Camera1->setStyleSheet(QString::fromUtf8(""));
        label_Camera1->setFrameShape(QFrame::Panel);
        label_Camera2 = new QLabel(centralwidget);
        label_Camera2->setObjectName("label_Camera2");
        label_Camera2->setGeometry(QRect(435, 540, 128, 121));
        label_Camera2->setFrameShape(QFrame::Panel);
        label_Camera3 = new QLabel(centralwidget);
        label_Camera3->setObjectName("label_Camera3");
        label_Camera3->setGeometry(QRect(565, 540, 128, 121));
        label_Camera3->setFrameShape(QFrame::Panel);
        label_Camera4 = new QLabel(centralwidget);
        label_Camera4->setObjectName("label_Camera4");
        label_Camera4->setGeometry(QRect(695, 540, 128, 121));
        label_Camera4->setFrameShape(QFrame::Panel);
        label_Camera5 = new QLabel(centralwidget);
        label_Camera5->setObjectName("label_Camera5");
        label_Camera5->setGeometry(QRect(825, 540, 128, 121));
        label_Camera5->setFrameShape(QFrame::Panel);
        label_F31 = new QLabel(centralwidget);
        label_F31->setObjectName("label_F31");
        label_F31->setGeometry(QRect(1070, 300, 10, 10));
        label_F31->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F31->setScaledContents(true);
        label_F22 = new QLabel(centralwidget);
        label_F22->setObjectName("label_F22");
        label_F22->setGeometry(QRect(1090, 305, 10, 10));
        label_F22->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F22->setScaledContents(true);
        label_F24 = new QLabel(centralwidget);
        label_F24->setObjectName("label_F24");
        label_F24->setGeometry(QRect(1130, 305, 10, 10));
        label_F24->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F24->setScaledContents(true);
        label_F34 = new QLabel(centralwidget);
        label_F34->setObjectName("label_F34");
        label_F34->setGeometry(QRect(1150, 300, 10, 10));
        label_F34->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F34->setScaledContents(true);
        label_F41 = new QLabel(centralwidget);
        label_F41->setObjectName("label_F41");
        label_F41->setGeometry(QRect(1080, 290, 10, 10));
        label_F41->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F41->setScaledContents(true);
        label_F32 = new QLabel(centralwidget);
        label_F32->setObjectName("label_F32");
        label_F32->setGeometry(QRect(1100, 290, 10, 10));
        label_F32->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F32->setScaledContents(true);
        label_F33 = new QLabel(centralwidget);
        label_F33->setObjectName("label_F33");
        label_F33->setGeometry(QRect(1120, 290, 10, 10));
        label_F33->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F33->setScaledContents(true);
        label_F43 = new QLabel(centralwidget);
        label_F43->setObjectName("label_F43");
        label_F43->setGeometry(QRect(1140, 290, 10, 10));
        label_F43->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F43->setScaledContents(true);
        label_F51 = new QLabel(centralwidget);
        label_F51->setObjectName("label_F51");
        label_F51->setGeometry(QRect(1090, 280, 10, 10));
        label_F51->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F51->setScaledContents(true);
        label_F42 = new QLabel(centralwidget);
        label_F42->setObjectName("label_F42");
        label_F42->setGeometry(QRect(1110, 280, 10, 10));
        label_F42->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F42->setScaledContents(true);
        label_F52 = new QLabel(centralwidget);
        label_F52->setObjectName("label_F52");
        label_F52->setGeometry(QRect(1130, 280, 10, 10));
        label_F52->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F52->setScaledContents(true);
        label_F61 = new QLabel(centralwidget);
        label_F61->setObjectName("label_F61");
        label_F61->setGeometry(QRect(1100, 270, 10, 10));
        label_F61->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F61->setScaledContents(true);
        label_F62 = new QLabel(centralwidget);
        label_F62->setObjectName("label_F62");
        label_F62->setGeometry(QRect(1120, 270, 10, 10));
        label_F62->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F62->setScaledContents(true);
        label_F71 = new QLabel(centralwidget);
        label_F71->setObjectName("label_F71");
        label_F71->setGeometry(QRect(1110, 260, 10, 10));
        label_F71->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F71->setScaledContents(true);
        label_F21 = new QLabel(centralwidget);
        label_F21->setObjectName("label_F21");
        label_F21->setGeometry(QRect(1070, 315, 10, 10));
        label_F21->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F21->setScaledContents(true);
        label_F25 = new QLabel(centralwidget);
        label_F25->setObjectName("label_F25");
        label_F25->setGeometry(QRect(1150, 315, 10, 10));
        label_F25->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F25->setScaledContents(true);
        label_F23 = new QLabel(centralwidget);
        label_F23->setObjectName("label_F23");
        label_F23->setGeometry(QRect(1110, 300, 10, 10));
        label_F23->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F23->setScaledContents(true);
        label_B71 = new QLabel(centralwidget);
        label_B71->setObjectName("label_B71");
        label_B71->setGeometry(QRect(1110, 540, 10, 10));
        label_B71->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B71->setScaledContents(true);
        label_B25 = new QLabel(centralwidget);
        label_B25->setObjectName("label_B25");
        label_B25->setGeometry(QRect(1070, 485, 10, 10));
        label_B25->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B25->setScaledContents(true);
        label_B22 = new QLabel(centralwidget);
        label_B22->setObjectName("label_B22");
        label_B22->setGeometry(QRect(1130, 495, 10, 10));
        label_B22->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B22->setScaledContents(true);
        label_B43 = new QLabel(centralwidget);
        label_B43->setObjectName("label_B43");
        label_B43->setGeometry(QRect(1080, 510, 10, 10));
        label_B43->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B43->setScaledContents(true);
        label_B52 = new QLabel(centralwidget);
        label_B52->setObjectName("label_B52");
        label_B52->setGeometry(QRect(1090, 520, 10, 10));
        label_B52->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B52->setScaledContents(true);
        label_B41 = new QLabel(centralwidget);
        label_B41->setObjectName("label_B41");
        label_B41->setGeometry(QRect(1140, 510, 10, 10));
        label_B41->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B41->setScaledContents(true);
        label_B21 = new QLabel(centralwidget);
        label_B21->setObjectName("label_B21");
        label_B21->setGeometry(QRect(1150, 485, 10, 10));
        label_B21->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B21->setScaledContents(true);
        label_B31 = new QLabel(centralwidget);
        label_B31->setObjectName("label_B31");
        label_B31->setGeometry(QRect(1150, 500, 10, 10));
        label_B31->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B31->setScaledContents(true);
        label_B51 = new QLabel(centralwidget);
        label_B51->setObjectName("label_B51");
        label_B51->setGeometry(QRect(1130, 520, 10, 10));
        label_B51->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B51->setScaledContents(true);
        label_B62 = new QLabel(centralwidget);
        label_B62->setObjectName("label_B62");
        label_B62->setGeometry(QRect(1100, 530, 10, 10));
        label_B62->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B62->setScaledContents(true);
        label_B61 = new QLabel(centralwidget);
        label_B61->setObjectName("label_B61");
        label_B61->setGeometry(QRect(1120, 530, 10, 10));
        label_B61->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B61->setScaledContents(true);
        label_B13 = new QLabel(centralwidget);
        label_B13->setObjectName("label_B13");
        label_B13->setGeometry(QRect(1110, 485, 10, 10));
        label_B13->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B13->setScaledContents(true);
        label_B42 = new QLabel(centralwidget);
        label_B42->setObjectName("label_B42");
        label_B42->setGeometry(QRect(1110, 520, 10, 10));
        label_B42->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B42->setScaledContents(true);
        label_B32 = new QLabel(centralwidget);
        label_B32->setObjectName("label_B32");
        label_B32->setGeometry(QRect(1120, 510, 10, 10));
        label_B32->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B32->setScaledContents(true);
        label_B23 = new QLabel(centralwidget);
        label_B23->setObjectName("label_B23");
        label_B23->setGeometry(QRect(1110, 500, 10, 10));
        label_B23->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B23->setScaledContents(true);
        label_B33 = new QLabel(centralwidget);
        label_B33->setObjectName("label_B33");
        label_B33->setGeometry(QRect(1100, 510, 10, 10));
        label_B33->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B33->setScaledContents(true);
        label_B34 = new QLabel(centralwidget);
        label_B34->setObjectName("label_B34");
        label_B34->setGeometry(QRect(1070, 500, 10, 10));
        label_B34->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B34->setScaledContents(true);
        label_B24 = new QLabel(centralwidget);
        label_B24->setObjectName("label_B24");
        label_B24->setGeometry(QRect(1090, 495, 10, 10));
        label_B24->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B24->setScaledContents(true);
        label_R61 = new QLabel(centralwidget);
        label_R61->setObjectName("label_R61");
        label_R61->setGeometry(QRect(1240, 390, 10, 10));
        label_R61->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R61->setScaledContents(true);
        label_R21 = new QLabel(centralwidget);
        label_R21->setObjectName("label_R21");
        label_R21->setGeometry(QRect(1195, 360, 10, 10));
        label_R21->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R21->setScaledContents(true);
        label_R13 = new QLabel(centralwidget);
        label_R13->setObjectName("label_R13");
        label_R13->setGeometry(QRect(1195, 400, 10, 10));
        label_R13->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R13->setScaledContents(true);
        label_R22 = new QLabel(centralwidget);
        label_R22->setObjectName("label_R22");
        label_R22->setGeometry(QRect(1205, 380, 10, 10));
        label_R22->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R22->setScaledContents(true);
        label_R42 = new QLabel(centralwidget);
        label_R42->setObjectName("label_R42");
        label_R42->setGeometry(QRect(1230, 400, 10, 10));
        label_R42->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R42->setScaledContents(true);
        label_R62 = new QLabel(centralwidget);
        label_R62->setObjectName("label_R62");
        label_R62->setGeometry(QRect(1240, 410, 10, 10));
        label_R62->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R62->setScaledContents(true);
        label_R71 = new QLabel(centralwidget);
        label_R71->setObjectName("label_R71");
        label_R71->setGeometry(QRect(1250, 400, 10, 10));
        label_R71->setStyleSheet(QString::fromUtf8(""));
        label_R71->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R71->setScaledContents(true);
        label_R51 = new QLabel(centralwidget);
        label_R51->setObjectName("label_R51");
        label_R51->setGeometry(QRect(1230, 380, 10, 10));
        label_R51->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R51->setScaledContents(true);
        label_R31 = new QLabel(centralwidget);
        label_R31->setObjectName("label_R31");
        label_R31->setGeometry(QRect(1210, 360, 10, 10));
        label_R31->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R31->setScaledContents(true);
        label_R43 = new QLabel(centralwidget);
        label_R43->setObjectName("label_R43");
        label_R43->setGeometry(QRect(1220, 430, 10, 10));
        label_R43->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R43->setScaledContents(true);
        label_R33 = new QLabel(centralwidget);
        label_R33->setObjectName("label_R33");
        label_R33->setGeometry(QRect(1220, 410, 10, 10));
        label_R33->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R33->setScaledContents(true);
        label_R41 = new QLabel(centralwidget);
        label_R41->setObjectName("label_R41");
        label_R41->setGeometry(QRect(1220, 370, 10, 10));
        label_R41->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R41->setScaledContents(true);
        label_R32 = new QLabel(centralwidget);
        label_R32->setObjectName("label_R32");
        label_R32->setGeometry(QRect(1220, 390, 10, 10));
        label_R32->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R32->setScaledContents(true);
        label_R24 = new QLabel(centralwidget);
        label_R24->setObjectName("label_R24");
        label_R24->setGeometry(QRect(1205, 420, 10, 10));
        label_R24->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R24->setScaledContents(true);
        label_R52 = new QLabel(centralwidget);
        label_R52->setObjectName("label_R52");
        label_R52->setGeometry(QRect(1230, 420, 10, 10));
        label_R52->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R52->setScaledContents(true);
        label_R23 = new QLabel(centralwidget);
        label_R23->setObjectName("label_R23");
        label_R23->setGeometry(QRect(1210, 400, 10, 10));
        label_R23->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R23->setScaledContents(true);
        label_R25 = new QLabel(centralwidget);
        label_R25->setObjectName("label_R25");
        label_R25->setGeometry(QRect(1195, 440, 10, 10));
        label_R25->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R25->setScaledContents(true);
        label_R34 = new QLabel(centralwidget);
        label_R34->setObjectName("label_R34");
        label_R34->setGeometry(QRect(1210, 440, 10, 10));
        label_R34->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R34->setScaledContents(true);
        label_L21 = new QLabel(centralwidget);
        label_L21->setObjectName("label_L21");
        label_L21->setGeometry(QRect(1025, 440, 10, 10));
        label_L21->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L21->setScaledContents(true);
        label_L22 = new QLabel(centralwidget);
        label_L22->setObjectName("label_L22");
        label_L22->setGeometry(QRect(1015, 420, 10, 10));
        label_L22->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L22->setScaledContents(true);
        label_L25 = new QLabel(centralwidget);
        label_L25->setObjectName("label_L25");
        label_L25->setGeometry(QRect(1025, 360, 10, 10));
        label_L25->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L25->setScaledContents(true);
        label_L33 = new QLabel(centralwidget);
        label_L33->setObjectName("label_L33");
        label_L33->setGeometry(QRect(1000, 390, 10, 10));
        label_L33->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L33->setScaledContents(true);
        label_L31 = new QLabel(centralwidget);
        label_L31->setObjectName("label_L31");
        label_L31->setGeometry(QRect(1010, 440, 10, 10));
        label_L31->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L31->setScaledContents(true);
        label_L52 = new QLabel(centralwidget);
        label_L52->setObjectName("label_L52");
        label_L52->setGeometry(QRect(990, 380, 10, 10));
        label_L52->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L52->setScaledContents(true);
        label_L71 = new QLabel(centralwidget);
        label_L71->setObjectName("label_L71");
        label_L71->setGeometry(QRect(970, 400, 10, 10));
        label_L71->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L71->setScaledContents(true);
        label_L43 = new QLabel(centralwidget);
        label_L43->setObjectName("label_L43");
        label_L43->setGeometry(QRect(1000, 370, 10, 10));
        label_L43->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L43->setScaledContents(true);
        label_L61 = new QLabel(centralwidget);
        label_L61->setObjectName("label_L61");
        label_L61->setGeometry(QRect(980, 410, 10, 10));
        label_L61->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L61->setScaledContents(true);
        label_L41 = new QLabel(centralwidget);
        label_L41->setObjectName("label_L41");
        label_L41->setGeometry(QRect(1000, 430, 10, 10));
        label_L41->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L41->setScaledContents(true);
        label_L62 = new QLabel(centralwidget);
        label_L62->setObjectName("label_L62");
        label_L62->setGeometry(QRect(980, 390, 10, 10));
        label_L62->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L62->setScaledContents(true);
        label_L32 = new QLabel(centralwidget);
        label_L32->setObjectName("label_L32");
        label_L32->setGeometry(QRect(1000, 410, 10, 10));
        label_L32->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L32->setScaledContents(true);
        label_L51 = new QLabel(centralwidget);
        label_L51->setObjectName("label_L51");
        label_L51->setGeometry(QRect(990, 420, 10, 10));
        label_L51->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L51->setScaledContents(true);
        label_L42 = new QLabel(centralwidget);
        label_L42->setObjectName("label_L42");
        label_L42->setGeometry(QRect(990, 400, 10, 10));
        label_L42->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L42->setScaledContents(true);
        label_L23 = new QLabel(centralwidget);
        label_L23->setObjectName("label_L23");
        label_L23->setGeometry(QRect(1010, 400, 10, 10));
        label_L23->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L23->setScaledContents(true);
        label_L24 = new QLabel(centralwidget);
        label_L24->setObjectName("label_L24");
        label_L24->setGeometry(QRect(1015, 380, 10, 10));
        label_L24->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L24->setScaledContents(true);
        label_L34 = new QLabel(centralwidget);
        label_L34->setObjectName("label_L34");
        label_L34->setGeometry(QRect(1010, 360, 10, 10));
        label_L34->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L34->setScaledContents(true);
        label_F11 = new QLabel(centralwidget);
        label_F11->setObjectName("label_F11");
        label_F11->setGeometry(QRect(1070, 330, 10, 10));
        label_F11->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F11->setScaledContents(true);
        label_F15 = new QLabel(centralwidget);
        label_F15->setObjectName("label_F15");
        label_F15->setGeometry(QRect(1150, 330, 10, 10));
        label_F15->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F15->setScaledContents(true);
        label_F13 = new QLabel(centralwidget);
        label_F13->setObjectName("label_F13");
        label_F13->setGeometry(QRect(1110, 315, 10, 10));
        label_F13->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F13->setScaledContents(true);
        label_F12 = new QLabel(centralwidget);
        label_F12->setObjectName("label_F12");
        label_F12->setGeometry(QRect(1090, 320, 10, 10));
        label_F12->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F12->setScaledContents(true);
        label_F14 = new QLabel(centralwidget);
        label_F14->setObjectName("label_F14");
        label_F14->setGeometry(QRect(1130, 320, 10, 10));
        label_F14->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_F14->setScaledContents(true);
        label_L14 = new QLabel(centralwidget);
        label_L14->setObjectName("label_L14");
        label_L14->setGeometry(QRect(1030, 380, 10, 10));
        label_L14->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L14->setScaledContents(true);
        label_L12 = new QLabel(centralwidget);
        label_L12->setObjectName("label_L12");
        label_L12->setGeometry(QRect(1030, 420, 10, 10));
        label_L12->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L12->setScaledContents(true);
        label_L15 = new QLabel(centralwidget);
        label_L15->setObjectName("label_L15");
        label_L15->setGeometry(QRect(1040, 360, 10, 10));
        label_L15->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L15->setScaledContents(true);
        label_L11 = new QLabel(centralwidget);
        label_L11->setObjectName("label_L11");
        label_L11->setGeometry(QRect(1040, 440, 10, 10));
        label_L11->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L11->setScaledContents(true);
        label_L13 = new QLabel(centralwidget);
        label_L13->setObjectName("label_L13");
        label_L13->setGeometry(QRect(1025, 400, 10, 10));
        label_L13->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_L13->setScaledContents(true);
        label_R14 = new QLabel(centralwidget);
        label_R14->setObjectName("label_R14");
        label_R14->setGeometry(QRect(1190, 420, 10, 10));
        label_R14->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R14->setScaledContents(true);
        label_R15 = new QLabel(centralwidget);
        label_R15->setObjectName("label_R15");
        label_R15->setGeometry(QRect(1180, 440, 10, 10));
        label_R15->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R15->setScaledContents(true);
        label_R12 = new QLabel(centralwidget);
        label_R12->setObjectName("label_R12");
        label_R12->setGeometry(QRect(1190, 380, 10, 10));
        label_R12->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R12->setScaledContents(true);
        label_R11 = new QLabel(centralwidget);
        label_R11->setObjectName("label_R11");
        label_R11->setGeometry(QRect(1180, 360, 10, 10));
        label_R11->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_R11->setScaledContents(true);
        label_B15 = new QLabel(centralwidget);
        label_B15->setObjectName("label_B15");
        label_B15->setGeometry(QRect(1070, 470, 10, 10));
        label_B15->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B15->setScaledContents(true);
        label_B11 = new QLabel(centralwidget);
        label_B11->setObjectName("label_B11");
        label_B11->setGeometry(QRect(1150, 470, 10, 10));
        label_B11->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B11->setScaledContents(true);
        label_B12 = new QLabel(centralwidget);
        label_B12->setObjectName("label_B12");
        label_B12->setGeometry(QRect(1130, 480, 10, 10));
        label_B12->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B12->setScaledContents(true);
        label_B14 = new QLabel(centralwidget);
        label_B14->setObjectName("label_B14");
        label_B14->setGeometry(QRect(1090, 480, 10, 10));
        label_B14->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Textures/Circle_Empty.png")));
        label_B14->setScaledContents(true);
        label_Compass = new QLabel(centralwidget);
        label_Compass->setObjectName("label_Compass");
        label_Compass->setGeometry(QRect(1062, 355, 102, 102));
        label_Compass->setPixmap(QPixmap(QString::fromUtf8(":/Resources/Icons/Compass.png")));
        label_Compass->setScaledContents(true);
        label_DroneCameraView = new QLabel(centralwidget);
        label_DroneCameraView->setObjectName("label_DroneCameraView");
        label_DroneCameraView->setGeometry(QRect(305, 50, 651, 481));
        label_DroneCameraView->setScaledContents(true);
        label_Camera1_2 = new QLabel(centralwidget);
        label_Camera1_2->setObjectName("label_Camera1_2");
        label_Camera1_2->setGeometry(QRect(305, 560, 124, 90));
        label_Camera1_2->setScaledContents(true);
        label_Camera2_2 = new QLabel(centralwidget);
        label_Camera2_2->setObjectName("label_Camera2_2");
        label_Camera2_2->setGeometry(QRect(435, 560, 124, 90));
        label_Camera2_2->setScaledContents(true);
        label_Camera3_2 = new QLabel(centralwidget);
        label_Camera3_2->setObjectName("label_Camera3_2");
        label_Camera3_2->setGeometry(QRect(565, 560, 124, 90));
        label_Camera3_2->setScaledContents(true);
        label_Camera5_2 = new QLabel(centralwidget);
        label_Camera5_2->setObjectName("label_Camera5_2");
        label_Camera5_2->setGeometry(QRect(825, 560, 124, 90));
        label_Camera5_2->setScaledContents(true);
        label_Camera4_2 = new QLabel(centralwidget);
        label_Camera4_2->setObjectName("label_Camera4_2");
        label_Camera4_2->setGeometry(QRect(695, 560, 124, 90));
        label_Camera4_2->setScaledContents(true);
        layoutWidget1 = new QWidget(centralwidget);
        layoutWidget1->setObjectName("layoutWidget1");
        layoutWidget1->setGeometry(QRect(960, 50, 316, 200));
        gridLayout = new QGridLayout(layoutWidget1);
        gridLayout->setObjectName("gridLayout");
        gridLayout->setContentsMargins(0, 0, 0, 0);
        lcdNumber_Height = new QLCDNumber(layoutWidget1);
        lcdNumber_Height->setObjectName("lcdNumber_Height");

        gridLayout->addWidget(lcdNumber_Height, 8, 1, 1, 1);

        lcdNumber_Speed = new QLCDNumber(layoutWidget1);
        lcdNumber_Speed->setObjectName("lcdNumber_Speed");

        gridLayout->addWidget(lcdNumber_Speed, 2, 1, 1, 1);

        lcdNumber_Displacement = new QLCDNumber(layoutWidget1);
        lcdNumber_Displacement->setObjectName("lcdNumber_Displacement");
        lcdNumber_Displacement->setSmallDecimalPoint(false);

        gridLayout->addWidget(lcdNumber_Displacement, 5, 1, 1, 1);

        label_Speed = new QLabel(layoutWidget1);
        label_Speed->setObjectName("label_Speed");

        gridLayout->addWidget(label_Speed, 0, 1, 1, 1);

        label_Displacement = new QLabel(layoutWidget1);
        label_Displacement->setObjectName("label_Displacement");

        gridLayout->addWidget(label_Displacement, 4, 1, 1, 1);

        label_Height = new QLabel(layoutWidget1);
        label_Height->setObjectName("label_Height");

        gridLayout->addWidget(label_Height, 6, 1, 1, 1);

        label_Pressure = new QLabel(layoutWidget1);
        label_Pressure->setObjectName("label_Pressure");

        gridLayout->addWidget(label_Pressure, 0, 0, 1, 1);

        lcdNumber_Pressure = new QLCDNumber(layoutWidget1);
        lcdNumber_Pressure->setObjectName("lcdNumber_Pressure");

        gridLayout->addWidget(lcdNumber_Pressure, 2, 0, 1, 1);

        label_Humedity = new QLabel(layoutWidget1);
        label_Humedity->setObjectName("label_Humedity");

        gridLayout->addWidget(label_Humedity, 6, 0, 1, 1);

        lcdNumber_Humedity = new QLCDNumber(layoutWidget1);
        lcdNumber_Humedity->setObjectName("lcdNumber_Humedity");

        gridLayout->addWidget(lcdNumber_Humedity, 8, 0, 1, 1);

        lcdNumber_Temperature = new QLCDNumber(layoutWidget1);
        lcdNumber_Temperature->setObjectName("lcdNumber_Temperature");

        gridLayout->addWidget(lcdNumber_Temperature, 5, 0, 1, 1);

        label_Temperature = new QLabel(layoutWidget1);
        label_Temperature->setObjectName("label_Temperature");

        gridLayout->addWidget(label_Temperature, 4, 0, 1, 1);

        lcdNumber_ThrottleValue = new QLCDNumber(centralwidget);
        lcdNumber_ThrottleValue->setObjectName("lcdNumber_ThrottleValue");
        lcdNumber_ThrottleValue->setGeometry(QRect(890, 490, 40, 30));
        lcdNumber_ThrottleValue->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 199);\n"
"color: rgb(255, 255, 255);"));
        lcdNumber_ThrottleValue->setDigitCount(3);
        progressBar_BatteryCharge = new QProgressBar(centralwidget);
        progressBar_BatteryCharge->setObjectName("progressBar_BatteryCharge");
        progressBar_BatteryCharge->setGeometry(QRect(315, 110, 120, 20));
        progressBar_BatteryCharge->setValue(24);
        progressBar_BatteryCharge->setTextVisible(false);
        Quadcopter_MainWindow->setCentralWidget(centralwidget);
        layoutWidget->raise();
        label_Camera5_2->raise();
        label_Camera4_2->raise();
        label_Camera3_2->raise();
        label_Camera2_2->raise();
        label_Camera1_2->raise();
        label_DroneCameraView->raise();
        pushButton_MoveLeft->raise();
        label_Compass->raise();
        pushButton_MoveForward->raise();
        label_Camera5->raise();
        label_Camera4->raise();
        label_Camera3->raise();
        label_Camera2->raise();
        label_Camera1->raise();
        graphicsView_DroneCameraView->raise();
        graphicsView_Camera3->raise();
        graphicsView_Camera4->raise();
        graphicsView_Camera2->raise();
        graphicsView_Camera1->raise();
        graphicsView_Camera0->raise();
        pushButton_MoveReverse->raise();
        pushButton_MoveRight->raise();
        dial_GeologicalPosition->raise();
        layoutWidget->raise();
        pushButton_DroneSelectPrevious->raise();
        pushButton_DroneSelectNext->raise();
        label_Time->raise();
        pushButton_DroneCameraSnapshot->raise();
        verticalSlider_Throttle->raise();
        label_Logo->raise();
        label_F31->raise();
        label_F22->raise();
        label_F24->raise();
        label_F34->raise();
        label_F41->raise();
        label_F32->raise();
        label_F33->raise();
        label_F43->raise();
        label_F51->raise();
        label_F42->raise();
        label_F52->raise();
        label_F61->raise();
        label_F62->raise();
        label_F71->raise();
        label_F21->raise();
        label_F25->raise();
        label_F23->raise();
        label_B71->raise();
        label_B25->raise();
        label_B22->raise();
        label_B43->raise();
        label_B52->raise();
        label_B41->raise();
        label_B21->raise();
        label_B31->raise();
        label_B51->raise();
        label_B62->raise();
        label_B61->raise();
        label_B13->raise();
        label_B42->raise();
        label_B32->raise();
        label_B23->raise();
        label_B33->raise();
        label_B34->raise();
        label_B24->raise();
        label_R61->raise();
        label_R21->raise();
        label_R13->raise();
        label_R22->raise();
        label_R42->raise();
        label_R62->raise();
        label_R71->raise();
        label_R51->raise();
        label_R31->raise();
        label_R43->raise();
        label_R33->raise();
        label_R41->raise();
        label_R32->raise();
        label_R24->raise();
        label_R52->raise();
        label_R23->raise();
        label_R25->raise();
        label_R34->raise();
        label_L21->raise();
        label_L22->raise();
        label_L25->raise();
        label_L33->raise();
        label_L31->raise();
        label_L52->raise();
        label_L71->raise();
        label_L43->raise();
        label_L61->raise();
        label_L41->raise();
        label_L62->raise();
        label_L32->raise();
        label_L51->raise();
        label_L42->raise();
        label_L23->raise();
        label_L24->raise();
        label_L34->raise();
        label_F11->raise();
        label_F15->raise();
        label_F13->raise();
        label_F12->raise();
        label_F14->raise();
        label_L14->raise();
        label_L12->raise();
        label_L15->raise();
        label_L11->raise();
        label_L13->raise();
        label_R14->raise();
        label_R15->raise();
        label_R12->raise();
        label_R11->raise();
        label_B15->raise();
        label_B11->raise();
        label_B12->raise();
        label_B14->raise();
        lcdNumber_ThrottleValue->raise();
        progressBar_BatteryCharge->raise();

        retranslateUi(Quadcopter_MainWindow);

        QMetaObject::connectSlotsByName(Quadcopter_MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *Quadcopter_MainWindow)
    {
        Quadcopter_MainWindow->setWindowTitle(QCoreApplication::translate("Quadcopter_MainWindow", "Quadcopter_MainWindow", nullptr));
        pushButton_DroneSelectPrevious->setText(QString());
        pushButton_DroneSelectNext->setText(QString());
        label_Time->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#ffffff;\">00:00:00</span></p></body></html>", nullptr));
        pushButton_DroneCameraSnapshot->setText(QString());
        pushButton_MoveForward->setText(QString());
        pushButton_MoveLeft->setText(QString());
        pushButton_MoveReverse->setText(QString());
        pushButton_MoveRight->setText(QString());
        pushButton_ConnectLoRaWAN->setText(QCoreApplication::translate("Quadcopter_MainWindow", "Search Drones", nullptr));
        label_Drones->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Drones</span></p></body></html>", nullptr));
        pushButton_ServerSetting->setText(QCoreApplication::translate("Quadcopter_MainWindow", "Server Setting", nullptr));
        label_MQTTTopic->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">MQTT Server:</span></p></body></html>", nullptr));
        label_MQTTQoS->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">LoRaWAN Server</span></p></body></html>", nullptr));
        label_StatusMQTTServer->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Disconnected</span></p></body></html>", nullptr));
        label_StatusLoRaWANServer->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Disconnected</span></p></body></html>", nullptr));
        label_DronesNumber->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">N/A</span></p></body></html>", nullptr));
        pushButton_SaveLogFile->setText(QCoreApplication::translate("Quadcopter_MainWindow", "Save Log File", nullptr));
        plainTextEdit_LogPanel->setPlainText(QString());
        label_QuadcopterConsole->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Drone - Console</span></p></body></html>", nullptr));
        label_Logo->setText(QString());
        label_Camera1->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 1</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_Camera2->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 2</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_Camera3->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 3</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_Camera4->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 4</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_Camera5->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Camera 5</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>", nullptr));
        label_F31->setText(QString());
        label_F22->setText(QString());
        label_F24->setText(QString());
        label_F34->setText(QString());
        label_F41->setText(QString());
        label_F32->setText(QString());
        label_F33->setText(QString());
        label_F43->setText(QString());
        label_F51->setText(QString());
        label_F42->setText(QString());
        label_F52->setText(QString());
        label_F61->setText(QString());
        label_F62->setText(QString());
        label_F71->setText(QString());
        label_F21->setText(QString());
        label_F25->setText(QString());
        label_F23->setText(QString());
        label_B71->setText(QString());
        label_B25->setText(QString());
        label_B22->setText(QString());
        label_B43->setText(QString());
        label_B52->setText(QString());
        label_B41->setText(QString());
        label_B21->setText(QString());
        label_B31->setText(QString());
        label_B51->setText(QString());
        label_B62->setText(QString());
        label_B61->setText(QString());
        label_B13->setText(QString());
        label_B42->setText(QString());
        label_B32->setText(QString());
        label_B23->setText(QString());
        label_B33->setText(QString());
        label_B34->setText(QString());
        label_B24->setText(QString());
        label_R61->setText(QString());
        label_R21->setText(QString());
        label_R13->setText(QString());
        label_R22->setText(QString());
        label_R42->setText(QString());
        label_R62->setText(QString());
        label_R71->setText(QString());
        label_R51->setText(QString());
        label_R31->setText(QString());
        label_R43->setText(QString());
        label_R33->setText(QString());
        label_R41->setText(QString());
        label_R32->setText(QString());
        label_R24->setText(QString());
        label_R52->setText(QString());
        label_R23->setText(QString());
        label_R25->setText(QString());
        label_R34->setText(QString());
        label_L21->setText(QString());
        label_L22->setText(QString());
        label_L25->setText(QString());
        label_L33->setText(QString());
        label_L31->setText(QString());
        label_L52->setText(QString());
        label_L71->setText(QString());
        label_L43->setText(QString());
        label_L61->setText(QString());
        label_L41->setText(QString());
        label_L62->setText(QString());
        label_L32->setText(QString());
        label_L51->setText(QString());
        label_L42->setText(QString());
        label_L23->setText(QString());
        label_L24->setText(QString());
        label_L34->setText(QString());
        label_F11->setText(QString());
        label_F15->setText(QString());
        label_F13->setText(QString());
        label_F12->setText(QString());
        label_F14->setText(QString());
        label_L14->setText(QString());
        label_L12->setText(QString());
        label_L15->setText(QString());
        label_L11->setText(QString());
        label_L13->setText(QString());
        label_R14->setText(QString());
        label_R15->setText(QString());
        label_R12->setText(QString());
        label_R11->setText(QString());
        label_B15->setText(QString());
        label_B11->setText(QString());
        label_B12->setText(QString());
        label_B14->setText(QString());
        label_Compass->setText(QString());
        label_DroneCameraView->setText(QString());
        label_Camera1_2->setText(QString());
        label_Camera2_2->setText(QString());
        label_Camera3_2->setText(QString());
        label_Camera5_2->setText(QString());
        label_Camera4_2->setText(QString());
        label_Speed->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Speed (m/s)</span></p></body></html>", nullptr));
        label_Displacement->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Displacement (cm)</span></p></body></html>", nullptr));
        label_Height->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Height (cm)</span></p></body></html>", nullptr));
        label_Pressure->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Pressure (Pa)</span></p></body></html>", nullptr));
        label_Humedity->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Humedity (%)</span></p></body></html>", nullptr));
        label_Temperature->setText(QCoreApplication::translate("Quadcopter_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Temperature (</span><span style=\" font-family:'Google Sans','arial','sans-serif'; font-size:20px; font-weight:500; color:#040c28; background-color:#ffffff;\">\302\260</span><span style=\" font-size:12pt;\">C)</span></p></body></html>", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Quadcopter_MainWindow: public Ui_Quadcopter_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_QUADCOPTER_MAINWINDOW_H
